### ISSUE TITLE
Downloader fails on `atrac17/coin-op_collection`

### ISSUE THREAD

**Issue by frarees** [theypsilon/Update_All_MiSTer#105]
Is this a problem with the updater or with my setup? Thanks!

```
################################################################################
SECTION: atrac17/coin-op_collection

Removing /media/fat/_Arcade/Hellfire (2P set).mra (/media/fat/_Arcade/Hellfire (2P set).mra)
Removing /media/fat/_Arcade/Zero Wing (2P set).mra (/media/fat/_Arcade/Zero Wing (2P set).mra)
Removing /media/fat/_Arcade/_alternatives/_Hellfire/Hellfire (1P set).mra (/media/fat/_Arcade/_alternatives/_Hellfire/Hellfire (1P set).mra)
Removing /media/fat/_Arcade/_alternatives/_Hellfire/Hellfire (1P set, older).mra (/media/fat/_Arcade/_alternatives/_Hellfire/Hellfire (1P set, older).mra)
Removing /media/fat/_Arcade/_alternatives/_Hellfire/Hellfire (2P set, older).mra (/media/fat/_Arcade/_alternatives/_Hellfire/Hellfire (2P set, older).mra)
Removing /media/fat/_Arcade/_alternatives/_Out Zone/Out Zone (Zero Wing TP-015 PCB conversion).mra (/media/fat/_Arcade/_alternatives/_Out Zone/Out Zone (Zero Wing TP-015 PCB conversion).mra)
Removing /media/fat/_Arcade/_alternatives/_Out Zone/Out Zone (harder).mra (/media/fat/_Arcade/_alternatives/_Out Zone/Out Zone (harder).mra)
Removing /media/fat/_Arcade/_alternatives/_Out Zone/Out Zone (old set).mra (/media/fat/_Arcade/_alternatives/_Out Zone/Out Zone (old set).mra)
Removing /media/fat/_Arcade/_alternatives/_Zero Wing/Zero Wing (1P set).mra (/media/fat/_Arcade/_alternatives/_Zero Wing/Zero Wing (1P set).mra)
Removing /media/fat/_Arcade/_alternatives/_Zero Wing/Zero Wing (2P set, Williams license).mra (/media/fat/_Arcade/_alternatives/_Zero Wing/Zero Wing (2P set, Williams license).mra)
Removing /media/fat/_Arcade/cores/prehisle_20220923.rbf (/media/fat/_Arcade/cores/prehisle_20220923.rbf)
Removing /media/fat/_Arcade/cores/toaplan1_20220516.rbf (/media/fat/_Arcade/cores/toaplan1_20220516.rbf)

Downloading 60 files:
Traceback (most recent call last):
  File "/tmp/tmpc92ra6qa/downloader/main.py", line 37, in main
    exit_code = execute_full_run(
  File "/tmp/tmpc92ra6qa/downloader/main.py", line 57, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/tmpc92ra6qa/downloader/full_run_service.py", line 59, in full_run
    result = self._full_run_impl()
  File "/tmp/tmpc92ra6qa/downloader/full_run_service.py", line 118, in _full_run_impl
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/tmpc92ra6qa/downloader/online_importer.py", line 102, in download_dbs_contents
    db_importer.process_changed_files(changed_files, needed_zips, filtered_zip_data)
  File "/tmp/tmpc92ra6qa/downloader/online_importer.py", line 639, in process_changed_files
    file_downloader.download_files(self._is_first_run())
  File "/tmp/tmpc92ra6qa/downloader/file_downloader.py", line 151, in download_files
    self._errors = self._download_try()
  File "/tmp/tmpc92ra6qa/downloader/file_downloader.py", line 182, in _download_try
    self._fetch_whole_queue(low_level)
  File "/tmp/tmpc92ra6qa/downloader/file_downloader.py", line 191, in _fetch_whole_queue
    target_path = self._prepare_target_path_in_whole_queue(file_path, file_description)
  File "/tmp/tmpc92ra6qa/downloader/file_downloader.py", line 212, in _prepare_target_path_in_whole_queue
    path_hash = self._file_system.hash(file_path)
  File "/tmp/tmpc92ra6qa/downloader/file_system.py", line 256, in hash
    return hash_file(self._path(path))
  File "/tmp/tmpc92ra6qa/downloader/file_system.py", line 433, in hash_file
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/fat/_Arcade/Hellfire (2P Set).mra'
```

**Comment by theypsilon** [comment]
I've just pushed a fix for this, please give it a try in 15 minutes, and let me know if everything went smooth.

**Comment by theypsilon** [comment]
Reopen if it didn't help please

**Comment by frarees** [comment]
Updated successfully, thanks!
